# Semana 6 · Normalización del dataset de Spotify

**Caso:** Spotify — capacidad de streaming y curaduría regional · **Autor:** Julián Andrés Solano Ledesma

Este cuaderno lleva el CSV plano de Kaggle (*Spotify Global Streaming Data 2024*, 500 filas × 12 columnas) al modelo del ERD (`diagrama-erd-spotify.svg`):

1. Perfila el archivo y comprueba las **dependencias funcionales** reales de los datos.
2. Resuelve la inconsistencia encontrada (el año de lanzamiento de cada álbum).
3. Separa las tablas del modelo y las valida en **SQLite** con `esquema-spotify.sql`.
4. Demuestra que la descomposición **no pierde información**: las uniones reconstruyen las 500 filas originales.

## 1. Carga y perfil del archivo

In [1]:
import sqlite3
from pathlib import Path

import pandas as pd

RUTA_CSV = Path("Spotify_2024_Global_Streaming_Data.csv")
RUTA_SQL = Path("esquema-spotify.sql")
SALIDA = Path("datos-normalizados")

plano = pd.read_csv(RUTA_CSV)
print(f"Filas: {len(plano)} · Columnas: {plano.shape[1]}")
print(f"Celdas nulas: {plano.isna().sum().sum()} · Filas duplicadas: {plano.duplicated().sum()}")
plano.head()

Filas: 500 · Columnas: 12
Celdas nulas: 0 · Filas duplicadas: 0

,Country,Artist,Album,Genre,Release Year,Monthly Listeners (Millions),Total Streams (Millions),Total Hours Streamed (Millions),Avg Stream Duration (Min),Platform Type,Streams Last 30 Days (Millions),Skip Rate (%)
0,Germany,Taylor Swift,1989 (Taylor's Version),K-pop,2019,23.10,3695.53,14240.35,4.28,Free,118.51,2.24
1,Brazil,The Weeknd,After Hours,R&B,2022,60.60,2828.16,11120.44,3.90,Premium,44.87,23.98
2,United States,Post Malone,Austin,Reggaeton,2023,42.84,1425.46,4177.49,4.03,Free,19.46,4.77
3,Italy,Ed Sheeran,Autumn Variations,K-pop,2018,73.24,2704.33,12024.08,3.26,Premium,166.05,25.12
4,Italy,Ed Sheeran,Autumn Variations,R&B,2023,7.89,3323.25,13446.32,4.47,Free,173.43,15.82

In [2]:
texto = ["Country", "Artist", "Album", "Genre", "Platform Type"]
plano[texto].nunique().rename("valores distintos").to_frame().T

                   Country  Artist  Album  Genre  Platform Type
valores distintos       20      15     15     10              2

## 2. Dependencias funcionales

`X → Y` se cumple si cada valor de `X` tiene **un solo** valor de `Y`. Esto decide dónde vive cada atributo en el modelo normalizado.

In [3]:
def depende(df, x, y):
    """Cuántos valores de x tienen más de un valor de y (0 = la dependencia se cumple)."""
    return int((df.groupby(x)[y].nunique() > 1).sum())


pruebas = [
    ("Album", "Artist"),
    ("Artist", "Album"),
    ("Album", "Release Year"),
    ("Album", "Genre"),
    ("Artist", "Genre"),
    ("Album", "Monthly Listeners (Millions)"),
]
resultado = pd.DataFrame(
    [(f"{x} → {y}", depende(plano, x, y), plano[x].nunique()) for x, y in pruebas],
    columns=["dependencia", "valores que la violan", "valores de X"],
)
resultado["¿se cumple?"] = resultado["valores que la violan"].eq(0).map({True: "sí", False: "no"})
resultado

,dependencia,valores que la violan,valores de X,¿se cumple?
0,Album → Artist,0,15,sí
1,Artist → Album,0,15,sí
2,Album → Release Year,15,15,no
3,Album → Genre,15,15,no
4,Artist → Genre,15,15,no
5,Album → Monthly Listeners (Millions),15,15,no

In [4]:
clave = ["Country", "Album", "Platform Type"]
repetidas = plano.duplicated(clave).sum()
print(f"(país, álbum, plan) se repite en {repetidas} filas → no sirve como clave; "
      "la tabla intermedia necesita una clave sustituta (metric_id).")

(país, álbum, plan) se repite en 158 filas → no sirve como clave; la tabla intermedia necesita una clave sustituta (metric_id).

## 3. La anomalía: el mismo álbum con varios años de lanzamiento

`Album → Release Year` debería cumplirse (un álbum sale una sola vez), pero en el archivo plano **cada álbum aparece con 6 años distintos**. Es la anomalía de actualización que la normalización evita: si el año vive en cada fila, nada impide que las copias se contradigan.

**Regla para resolverla:** se guarda un solo año por álbum, el más frecuente (moda); si hay empate, el menor. Es una regla reproducible, no una verificación del año real.

In [5]:
def moda_menor(s):
    conteo = s.value_counts()
    return int(conteo[conteo == conteo.max()].index.min())


anios = (plano.groupby("Album")["Release Year"]
              .agg(anios_distintos="nunique",
                   valores=lambda s: sorted(s.unique()),
                   anio_elegido=moda_menor)
              .reset_index())
anios

,Album,anios_distintos,valores,anio_elegido
0,1989 (Taylor's Version),6,"[2018, 2019, 2020, 2021, 2022, 2023]",2020
1,After Hours,6,"[2018, 2019, 2020, 2021, 2022, 2023]",2023
2,Austin,6,"[2018, 2019, 2020, 2021, 2022, 2023]",2019
3,Autumn Variations,6,"[2018, 2019, 2020, 2021, 2022, 2023]",2019
4,BORN PINK,6,"[2018, 2019, 2020, 2021, 2022, 2023]",2021
5,Eternal Sunshine,6,"[2018, 2019, 2020, 2021, 2022, 2023]",2020
6,For All The Dogs,6,"[2018, 2019, 2020, 2021, 2022, 2023]",2018
7,Future Nostalgia,6,"[2018, 2019, 2020, 2021, 2022, 2023]",2023
8,Guts,6,"[2018, 2019, 2020, 2021, 2022, 2023]",2022
9,Happier Than Ever,6,"[2018, 2019, 2020, 2021, 2022, 2023]",2019
10,MAÑANA SERÁ BONITO,6,"[2018, 2019, 2020, 2021, 2022, 2023]",2019
11,Nadie Sabe Lo Que Va a Pasar Mañana,6,"[2018, 2019, 2020, 2021, 2022, 2023]",2019
12,Proof,6,"[2018, 2019, 2020, 2021, 2022, 2023]",2023
13,SOS,6,"[2018, 2019, 2020, 2021, 2022, 2023]",2022
14,Scarlet,6,"[2018, 2019, 2020, 2021, 2022, 2023]",2022

## 4. Separar las tablas del modelo

In [6]:
# Catálogo de países: el CSV solo trae el nombre; se agregan código ISO 3166-1 y región.
PAISES = {
    "Argentina": ("AR", "Latinoamérica"), "Australia": ("AU", "Oceanía"),
    "Brazil": ("BR", "Latinoamérica"), "Canada": ("CA", "Norteamérica"),
    "France": ("FR", "Europa"), "Germany": ("DE", "Europa"), "India": ("IN", "Asia"),
    "Indonesia": ("ID", "Asia"), "Italy": ("IT", "Europa"), "Japan": ("JP", "Asia"),
    "Mexico": ("MX", "Latinoamérica"), "Netherlands": ("NL", "Europa"),
    "Russia": ("RU", "Europa"), "South Africa": ("ZA", "África"),
    "South Korea": ("KR", "Asia"), "Spain": ("ES", "Europa"), "Sweden": ("SE", "Europa"),
    "Turkey": ("TR", "Asia"), "United Kingdom": ("GB", "Europa"),
    "United States": ("US", "Norteamérica"),
}


def catalogo(valores, id_col):
    """Tabla de catálogo con id consecutivo en orden alfabético."""
    t = pd.DataFrame({"nombre": sorted(valores)})
    t.insert(0, id_col, range(1, len(t) + 1))
    return t


pais = catalogo(plano["Country"].unique(), "country_id")
pais.insert(1, "codigo_iso", pais["nombre"].map(lambda n: PAISES[n][0]))
pais["region"] = pais["nombre"].map(lambda n: PAISES[n][1])

genero = catalogo(plano["Genre"].unique(), "genero_id")
plan_suscripcion = catalogo(plano["Platform Type"].unique(), "plan_id")

artista = catalogo(plano["Artist"].unique(), "artist_id")
artista["genero_principal"] = None   # Artist → Genre no se cumple (sección 2)

album = (plano[["Album", "Artist"]].drop_duplicates()
         .merge(artista, left_on="Artist", right_on="nombre")
         .merge(anios[["Album", "anio_elegido"]], on="Album")
         .sort_values("artist_id").reset_index(drop=True))
album.insert(0, "album_id", range(1, len(album) + 1))
album = album.rename(columns={"Album": "titulo", "anio_elegido": "anio_lanzamiento"})[
    ["album_id", "artist_id", "titulo", "anio_lanzamiento"]]
album

    album_id  artist_id                               titulo  anio_lanzamiento
0          1          1                     Eternal Sunshine              2020
1          2          2                            BORN PINK              2021
2          3          3                                Proof              2023
3          4          4  Nadie Sabe Lo Que Va a Pasar Mañana              2019
4          5          5                    Happier Than Ever              2019
5          6          6                              Scarlet              2022
6          7          7                     For All The Dogs              2018
7          8          8                     Future Nostalgia              2023
8          9          9                    Autumn Variations              2019
9         10         10                   MAÑANA SERÁ BONITO              2019
10        11         11                                 Guts              2022
11        12         12                               Austin              2019
12        13         13                                  SOS              2022
13        14         14              1989 (Taylor's Version)              2020
14        15         15                          After Hours              2023

In [7]:
ids = lambda tabla, col, id_col: dict(zip(tabla[col], tabla[id_col]))

metrica_streaming = pd.DataFrame({
    "metric_id": range(1, len(plano) + 1),               # = número de fila en el CSV
    "country_id": plano["Country"].map(ids(pais, "nombre", "country_id")),
    "album_id": plano["Album"].map(ids(album, "titulo", "album_id")),
    "genero_id": plano["Genre"].map(ids(genero, "nombre", "genero_id")),
    "plan_id": plano["Platform Type"].map(ids(plan_suscripcion, "nombre", "plan_id")),
    "oyentes_mensuales_m": plano["Monthly Listeners (Millions)"],
    "streams_totales_m": plano["Total Streams (Millions)"],
    "horas_totales_m": plano["Total Hours Streamed (Millions)"],
    "duracion_prom_min": plano["Avg Stream Duration (Min)"],
    "streams_30d_m": plano["Streams Last 30 Days (Millions)"],
    "skip_rate_pct": plano["Skip Rate (%)"],
})
assert metrica_streaming.notna().all().all(), "Alguna FK quedó sin resolver"
metrica_streaming.head()

,metric_id,country_id,album_id,genero_id,plan_id,oyentes_mensuales_m,streams_totales_m,horas_totales_m,duracion_prom_min,streams_30d_m,skip_rate_pct
0,1,6,14,6,1,23.10,3695.53,14240.35,4.28,118.51,2.24
1,2,3,15,8,2,60.60,2828.16,11120.44,3.90,44.87,23.98
2,3,20,12,9,1,42.84,1425.46,4177.49,4.03,19.46,4.77
3,4,9,9,6,2,73.24,2704.33,12024.08,3.26,166.05,25.12
4,5,9,9,8,1,7.89,3323.25,13446.32,4.47,173.43,15.82

## 5. Validación en SQLite con el esquema del ERD

In [8]:
tablas = {
    "pais": pais, "genero": genero, "plan_suscripcion": plan_suscripcion,
    "artista": artista, "album": album, "metrica_streaming": metrica_streaming,
}

con = sqlite3.connect(":memory:")
con.executescript(RUTA_SQL.read_text(encoding="utf-8"))
for nombre, df in tablas.items():          # el orden respeta las FK: catálogos primero
    df.to_sql(nombre, con, if_exists="append", index=False)

violaciones = con.execute("PRAGMA foreign_key_check").fetchall()
print("Violaciones de FK:", violaciones or "ninguna")
pd.DataFrame({t: [con.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0]] for t in tablas},
             index=["filas"])

Violaciones de FK: ninguna

       pais  genero  plan_suscripcion  artista  album  metrica_streaming
filas    20      10                 2       15     15                500

In [9]:
# Las restricciones rechazan datos inválidos: una métrica que apunta a un álbum inexistente
try:
    con.execute("INSERT INTO metrica_streaming VALUES (9999, 1, 99, 1, 1, 1, 1, 1, 1, 1, 1)")
except sqlite3.IntegrityError as e:
    print("Rechazado por la FK:", e)

Rechazado por la FK: FOREIGN KEY constraint failed

## 6. Descomposición sin pérdida

Si la normalización es correcta, unir las tablas debe devolver **exactamente** el archivo original. La única columna que cambia es `Release Year`, porque ahora tiene un solo valor por álbum (sección 3).

In [10]:
reconstruido = pd.read_sql("""
    SELECT p.nombre  AS "Country",       ar.nombre AS "Artist",  al.titulo AS "Album",
           g.nombre  AS "Genre",         al.anio_lanzamiento AS "Release Year",
           m.oyentes_mensuales_m AS "Monthly Listeners (Millions)",
           m.streams_totales_m   AS "Total Streams (Millions)",
           m.horas_totales_m     AS "Total Hours Streamed (Millions)",
           m.duracion_prom_min   AS "Avg Stream Duration (Min)",
           ps.nombre AS "Platform Type",
           m.streams_30d_m       AS "Streams Last 30 Days (Millions)",
           m.skip_rate_pct       AS "Skip Rate (%)"
    FROM metrica_streaming m
    JOIN pais p              ON p.country_id = m.country_id
    JOIN album al            ON al.album_id  = m.album_id
    JOIN artista ar          ON ar.artist_id = al.artist_id
    JOIN genero g            ON g.genero_id  = m.genero_id
    JOIN plan_suscripcion ps ON ps.plan_id   = m.plan_id
    ORDER BY m.metric_id
""", con)

sin_anio = [c for c in plano.columns if c != "Release Year"]
pd.testing.assert_frame_equal(reconstruido[sin_anio], plano[sin_anio], check_dtype=False)
print(f"OK: las {len(reconstruido)} filas se reconstruyen idénticas en las 11 columnas restantes.")

OK: las 500 filas se reconstruyen idénticas en las 11 columnas restantes.

## 7. Qué se dejó de repetir

In [11]:
filas = len(plano)
resumen = pd.DataFrame([
    ("Nombre del país", "Country", "pais", len(pais)),
    ("Nombre del artista", "Artist", "artista", len(artista)),
    ("Título del álbum", "Album", "album", len(album)),
    ("Año de lanzamiento", "Release Year", "album", len(album)),
    ("Nombre del género", "Genre", "genero", len(genero)),
    ("Tipo de plan", "Platform Type", "plan_suscripcion", len(plan_suscripcion)),
], columns=["dato", "columna del CSV", "vive solo en", "veces que se guarda"])
resumen.insert(2, "veces en el CSV plano", filas)
resumen

,dato,columna del CSV,veces en el CSV plano,vive solo en,veces que se guarda
0,Nombre del país,Country,500,pais,20
1,Nombre del artista,Artist,500,artista,15
2,Título del álbum,Album,500,album,15
3,Año de lanzamiento,Release Year,500,album,15
4,Nombre del género,Genre,500,genero,10
5,Tipo de plan,Platform Type,500,plan_suscripcion,2

## 8. Exportar las tablas normalizadas

In [12]:
SALIDA.mkdir(exist_ok=True)
for nombre, df in tablas.items():
    df.to_csv(SALIDA / f"{nombre}.csv", index=False)
    print(f"{nombre + '.csv':<24} {len(df):>4} filas")
con.close()

pais.csv                   20 filas
genero.csv                 10 filas
plan_suscripcion.csv        2 filas
artista.csv                15 filas
album.csv                  15 filas
metrica_streaming.csv     500 filas